# Site settings
title: "Yang Peng's Home Page"
email: yangpeng@caltech.edu 
description: > # this means to ignore newlines until "baseurl:"
    Yang Peng is a postdoctoral scholar in theoretical condensed matter Physics in Caltech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pengyangraul.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Other options
#permalink: notes/:year/:month/:title
job.title: "Postdoc"
excerpt_separator: "<!--more-->"

